
#line 2 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[372] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  119,  117,
      116,  116,  104,  117,  117,  110,  103,  117,   98,   99,
      108,  107,   95,  106,  102,  109,   58,   58,   96,   92,
      111,   97,  112,  115,   57,   57,  100,  101,  113,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   93,  114,   94,  105,
       10,    9,    8,    7,    8,    8,    4,    3,    4,    4,
       91,    0,   69,    0,    0,   77,   94,   86,   78,    0,
        0,   75,   83,   73,   84,   74,   85,    0,   64,   13,
       11,   76,   65,   58,    0,   61,   61,    0,   61,   58,

      101,   93,  100,   82,   88,   90,   89,   81,   57,    0,
        0,   79,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   23,   57,   57,   57,   57,   57,   57,   31,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   80,   87,    5,    6,    1,    2,    0,
       62,   70,    0,   64,    0,   64,    0,   65,   60,   60,
       60,    0,   63,   61,   61,   61,   61,    0,   59,   72,
       71,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   29,   57,   57,   34,
       57,   52,   51,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   57,    0,    0,
       64,    0,    0,   64,    0,   65,   60,   60,   60,   60,
       63,   61,   67,   68,   59,    0,   59,   59,   57,   57,
       57,   14,   57,   17,   57,   18,   57,   57,   57,   57,
       25,   26,   57,   57,   57,   30,   57,   35,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       48,   57,   57,    0,    0,    0,   64,   60,   67,    0,
       67,   68,    0,   59,   59,    0,   66,   59,   59,   15,
       57,   57,   16,   53,   20,   57,   57,   57,   57,   28,
       57,   57,   57,   57,   57,   39,   57,   57,   57,   57,

       57,   57,   46,   57,   57,   50,    0,    0,    0,   67,
       67,    0,    0,   68,   66,   59,   57,   57,   57,   57,
       24,   27,   54,   33,   57,   57,   38,   40,   41,   42,
       43,   44,   57,   57,   57,    0,    0,    0,   67,   57,
       57,   57,   22,   57,   57,   45,   57,   57,    0,   12,
       19,   57,   21,   36,   37,   47,   49,    0,    0,   57,
        0,    0,   32,    0,    0,    0,   55,    0,    0,   56,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   31,
       32,   32,   33,   32,   32,   34,   32,   32,   32,   35,
       32,   32,   32,   32,   36,   32,   32,   37,   32,   32,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   32,   52,   53,   54,   55,
       56,   57,   32,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    4,    1,    5,    5,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    6,    6,    7,    7,    6,    6,    1,    1,    1,
        1,    6,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    7,    6,    6,    6,    7,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[381] =
    {   0,
        0,    0,  576,  575,   68,   69,   70,   71,  577,  580,
      580,  580,  552,   69,  518,   52,   69,  535,  580,  580,
      549,   66,  580,   75,   75,   83,   92,   85,  547,  580,
      110,  547,   73,  580,    0,  100,  580,  580,  546,  107,
      508,  510,   94,   67,   94,   60,  511,   69,  510,  100,
      518,  104,  499,  508,  506,  511,  580,  101,  580,  580,
      580,  580,  580,  580,  542,  546,  580,  580,  540,  544,
      580,  121,  580,    0,  498,  580,  580,  580,  580,  120,
      545,  580,  580,  580,  580,  580,  580,  537,  142,  549,
      580,  580,  151,  158,  177,  166,  131,  535,  165,  195,

      580,  580,  580,  527,  580,  580,  580,  526,    0,  168,
      510,  580,  492,  491,  492,  485,  497,  484,  491,  498,
      485,  491,  477,  478,  475,  475,  478,  475,  472,    0,
      126,  476,  466,  474,  157,  472,   54,   99,  476,  469,
      162,  115,  474,  580,  580,  580,  580,  580,  580,  481,
      580,  580,  214,  580,  494,  216,  224,  580,  188,  186,
      201,  189,  239,  196,  580,  488,  468,    0,  243,  580,
      580,  464,  465,  475,  461,  473,  468,  461,  455,  192,
      469,  467,  463,  455,  461,  167,    0,  451,  455,    0,
      456,    0,    0,  453,  443,  441,  443,  445,  452,  438,

      436,  436,  448,  438,  442,  446,  448,  437,  440,  246,
      255,  435,  274,  580,  248,  264,  219,  580,  453,  433,
      580,  580,  267,  272,  275,  299,  219,  261,  432,  427,
      434,    0,  430,    0,  435,    0,  420,  428,  417,  424,
        0,    0,  418,  415,  416,    0,  418,    0,  413,  413,
      412,  409,  421,  411,  415,  420,  419,  417,  407,  412,
        0,  400,  412,  404,  414,  262,  307,  580,  580,  314,
      297,  580,  323,  249,  580,  325,  327,  422,  402,    0,
      401,  402,    0,    0,    0,  397,  398,  403,  393,    0,
      391,  389,  369,  354,  348,    0,  356,  352,  353,  337,

      346,  348,    0,  339,  342,    0,  349,  326,  329,  333,
      580,  343,  346,  351,  580,  580,  342,  333,  322,  319,
        0,    0,    0,    0,  330,  331,    0,    0,    0,    0,
        0,    0,  326,  309,  298,  336,  320,  349,  353,  257,
      273,  258,    0,  241,  231,    0,  230,  224,  331,  580,
        0,  203,    0,    0,    0,    0,    0,  190,  196,  138,
      141,  127,    0,  121,  106,  107,  580,   92,   28,  580,
      580,  406,  413,  420,  427,  434,  437,  441,   74,  442
    } ;

static const flex_int16_t yy_def[381] =
    {   0,
      371,    1,  372,  372,  373,  373,  374,  374,  371,  371,
      371,  371,  371,  375,  371,  371,  371,  376,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  377,  377,  371,  371,  371,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  375,  371,  375,  371,  371,  371,  371,  371,  376,
      376,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  378,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  377,  375,
      376,  371,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  379,  378,  371,
      371,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  379,  380,  371,  371,  371,  371,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  371,  371,  371,  371,  371,  371,  371,
      380,  371,  371,  371,  371,  371,  371,  371,  371,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  371,  371,  371,  371,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  371,  371,
      377,  377,  377,  377,  377,  377,  377,  371,  371,  377,
      371,  371,  377,  371,  371,  371,  371,  371,  371,  371,
        0,  371,  371,  371,  371,  371,  371,  371,  371,  371
    } ;

static const flex_int16_t yy_nxt[651] =
    {   0,
       10,   11,   12,   11,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   35,   35,   35,
       35,   35,   35,   36,   35,   35,   35,   37,   10,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   35,
       48,   35,   49,   50,   35,   35,   35,   51,   52,   53,
       54,   55,   56,   35,   35,   35,   57,   58,   59,   60,
       64,   64,   68,   68,   73,   76,   77,   78,  223,   83,
       65,   65,   69,   69,  370,   66,   66,   70,   70,   84,
       85,   88,   79,   89,   89,   90,  107,  108,   86,   87,

       91,   93,  198,  100,  100,  110,   92,   74,   93,  111,
       94,   94,  127,  122,   95,  128,  130,  102,   96,  199,
       97,   95,  123,  131,  144,   96,   73,   97,   98,  151,
      103,   95,  104,  105,  113,  114,  118,   99,   95,  115,
      119,  200,  133,  120,   99,   97,  124,  369,  125,  121,
      134,  368,   97,  136,  137,   98,  201,  126,   81,   74,
       89,   89,  367,  138,  166,  206,  139,  207,  145,  156,
      156,  153,  154,   73,   93,  154,   94,   94,  189,  366,
      157,  158,  365,  167,  158,  190,  364,   95,  153,  154,
      162,  159,  162,  160,  154,  163,  163,  157,  158,  164,

      165,  165,  363,  158,   95,  194,   74,  163,  163,  244,
      161,   93,  204,  100,  100,  195,  196,  164,  160,  219,
      205,  217,  245,  218,   95,  165,  165,  210,   96,  210,
       97,  165,  211,  211,  156,  156,  218,  215,  220,  215,
      362,   95,  216,  216,  361,  213,  214,   99,  218,  214,
      237,  238,  278,  217,  218,   97,  165,  163,  163,  224,
      360,  218,  213,  214,  211,  211,  216,  216,  214,  221,
      357,  279,  221,  211,  211,  356,  225,  226,  227,  218,
      267,  267,  216,  216,  275,  154,  221,  266,  154,  266,
      355,  221,  267,  267,  158,  228,  275,  158,  354,  226,

      269,  270,  154,  227,  353,  272,  273,  154,  274,  275,
      275,  158,  276,  274,  276,  352,  158,  277,  277,  269,
      351,  275,  350,  270,  272,  267,  267,  309,  273,  309,
      311,  312,  310,  310,  349,  275,  313,  214,  313,  349,
      214,  314,  314,  277,  277,  277,  277,  310,  310,  311,
      348,  310,  310,  312,  214,  347,  338,  315,  338,  214,
      315,  339,  339,  269,  314,  314,  269,  339,  339,  314,
      314,  339,  339,  346,  315,  345,  344,  358,  343,  315,
      269,  272,  342,  311,  272,  269,  311,  341,  340,  359,
      337,  336,  335,  334,  333,  332,  331,  330,  272,  329,

      311,  328,  327,  272,  326,  311,   61,   61,   61,   61,
       61,   61,   61,   63,   63,   63,   63,   63,   63,   63,
       67,   67,   67,   67,   67,   67,   67,   72,  325,   72,
       72,   72,   72,   72,   80,  324,  323,   80,   80,   80,
       80,  109,  109,  109,  169,  169,  271,  322,  271,  321,
      320,  319,  318,  317,  316,  316,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  268,  268,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,

      252,  251,  250,  249,  248,  247,  246,  243,  242,  241,
      240,  239,  236,  235,  234,  233,  232,  231,  230,  229,
      222,  222,  212,  209,  208,  203,  202,  197,  193,  192,
      191,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  172,   81,  171,
      170,  168,  155,  152,   80,  150,  149,  148,  147,  146,
      143,  142,  141,  140,  135,  132,  129,  117,  116,  112,
      106,  101,   82,   81,   75,   71,  371,   62,   62,    9,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371
    } ;

static const flex_int16_t yy_chk[651] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    6,    7,    8,   14,   16,   16,   17,  379,   22,
        5,    6,    7,    8,  369,    5,    6,    7,    8,   22,
       24,   25,   17,   25,   25,   26,   33,   33,   24,   24,

       26,   28,  137,   28,   28,   36,   26,   14,   27,   36,
       27,   27,   46,   44,   28,   46,   48,   31,   28,  137,
       28,   27,   44,   48,   58,   27,   72,   27,   27,   80,
       31,   28,   31,   31,   40,   40,   43,   28,   27,   40,
       43,  138,   50,   43,   27,   28,   45,  368,   45,   43,
       50,  366,   27,   52,   52,   27,  138,   45,   80,   72,
       89,   89,  365,   52,   97,  142,   52,  142,   58,   93,
       93,   89,   89,  110,   94,   89,   94,   94,  131,  364,
       93,   93,  362,   97,   93,  131,  361,   94,   89,   89,
       95,   94,   95,   94,   89,   95,   95,   93,   93,   96,

       99,   96,  360,   93,   94,  135,  110,  162,  162,  186,
       94,  100,  141,  100,  100,  135,  135,   99,   94,  160,
      141,  159,  186,  159,  100,   99,   96,  153,  100,  153,
      100,  164,  153,  153,  156,  156,  161,  157,  160,  157,
      359,  100,  157,  157,  358,  156,  156,  100,  159,  156,
      180,  180,  227,  161,  217,  100,  164,  163,  163,  169,
      352,  161,  156,  156,  210,  210,  215,  215,  156,  163,
      348,  227,  163,  211,  211,  347,  169,  169,  169,  217,
      266,  266,  216,  216,  274,  211,  163,  213,  211,  213,
      345,  163,  213,  213,  216,  169,  228,  216,  344,  169,

      223,  223,  211,  169,  342,  224,  224,  211,  225,  274,
      225,  216,  226,  228,  226,  341,  216,  226,  226,  223,
      340,  228,  337,  223,  224,  267,  267,  270,  224,  270,
      271,  271,  270,  270,  349,  225,  273,  267,  273,  336,
      267,  273,  273,  276,  276,  277,  277,  309,  309,  271,
      335,  310,  310,  271,  267,  334,  312,  277,  312,  267,
      277,  312,  312,  310,  313,  313,  310,  338,  338,  314,
      314,  339,  339,  333,  277,  326,  325,  349,  320,  277,
      310,  314,  319,  339,  314,  310,  339,  318,  317,  349,
      308,  307,  305,  304,  302,  301,  300,  299,  314,  298,

      339,  297,  295,  314,  294,  339,  372,  372,  372,  372,
      372,  372,  372,  373,  373,  373,  373,  373,  373,  373,
      374,  374,  374,  374,  374,  374,  374,  375,  293,  375,
      375,  375,  375,  375,  376,  292,  291,  376,  376,  376,
      376,  377,  377,  377,  378,  378,  380,  289,  380,  288,
      287,  286,  282,  281,  279,  278,  265,  264,  263,  262,
      260,  259,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  247,  245,  244,  243,  240,  239,  238,  237,
      235,  233,  231,  230,  229,  220,  219,  212,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,

      197,  196,  195,  194,  191,  189,  188,  185,  184,  183,
      182,  181,  179,  178,  177,  176,  175,  174,  173,  172,
      167,  166,  155,  150,  143,  140,  139,  136,  134,  133,
      132,  129,  128,  127,  126,  125,  124,  123,  122,  121,
      120,  119,  118,  117,  116,  115,  114,  113,  111,  108,
      104,   98,   90,   88,   81,   75,   70,   69,   66,   65,
       56,   55,   54,   53,   51,   49,   47,   42,   41,   39,
       32,   29,   21,   18,   15,   13,    9,    4,    3,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "source/scanner.l"
#line 3 "source/scanner.l"
   /*+------- <| --------------------------------------------------------**
    **         A                     Clan                                **
    **---     /.\   -----------------------------------------------------**
    **   <|  [""M#                 scanner.l                             **
    **-   A   | #   -----------------------------------------------------**
    **   /.\ [""M#         First version: 30/04/2008                     **
    **- [""M# | #  U"U#U  -----------------------------------------------**
         | #  | #  \ .:/
         | #  | #___| #
 ******  | "--'     .-"  ******************************************************
 *     |"-"-"-"-"-#-#-##   Clan : the Chunky Loop Analyzer (experimental)     *
 ****  |     # ## ######  *****************************************************
 *      \       .::::'/                                                       *
 *       \      ::::'/     Copyright (C) 2008 University Paris-Sud 11         *
 *     :8a|    # # ##                                                         *
 *     ::88a      ###      This is free software; you can redistribute it     *
 *    ::::888a  8a ##::.   and/or modify it under the terms of the GNU Lesser *
 *  ::::::::888a88a[]:::   General Public License as published by the Free    *
 *::8:::::::::SUNDOGa8a::. Software Foundation, either version 2.1 of the     *
 *::::::::8::::888:Y8888:: License, or (at your option) any later version.    *
 *::::':::88::::888::Y88a::::::::::::...                                      *
 *::'::..    .   .....   ..   ...  .                                          *
 * This software is distributed in the hope that it will be useful, but       *
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY *
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License   *
 * for more details.      *
 *                                                                            *
 * You should have received a copy of the GNU Lesser General Public License   *
 * along with software; if not, write to the Free Software Foundation, Inc.,  *
 * 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA                     *
 *                                                                            *
 * Clan, the Chunky Loop Analyzer                                             *
 * Written by Cedric Bastoul, Cedric.Bastoul@u-psud.fr                        *
 *                                                                            *
 ******************************************************************************/
   #include <stdlib.h>
   #include <string.h>
   
   #include <osl/vector.h>
   #include <osl/relation.h>
   #include <osl/relation_list.h>
   #include <osl/statement.h>
   #include <osl/scop.h>
   #include <parser.h>
   #include <clan/macros.h>
   #include <clan/symbol.h>
   #include <clan/options.h>

   void clan_scanner_count();
   int  clan_scanner(int, char*);
   void clan_scanner_initialize();

   extern int            parser_recording; /**< Do we record what we read? */
   extern char*          parser_record;    /**< What we record */
   extern clan_symbol_p  parser_symbol;    /**< Top of the symbol table */
   extern clan_options_p parser_options;   /**< Clan options */

   int   scanner_parsing;                  /**< Do we parse or not? */
   int   scanner_comment;                  /**< Comment nesting depth */
   char* scanner_latest_text;              /**< Latest text read */
   char* scanner_clay;                     /**< Data for the Clay software */
   int   scanner_line;                     /**< Current line number */
   int   scanner_column;                   /**< Current column number */
   int   scanner_column_LALR;              /**< Column number before token */
   int   scanner_scop_start;               /**< SCoP starting line */
   int   scanner_scop_end;                 /**< SCoP ending line */
   int   scanner_pragma;                   /**< Between SCoP pragmas or not? */
   int   scanner_space;                    /**< Are we reading spaces or not?*/
#line 778 "scanner.c"
#define YY_NO_INPUT 1

#line 781 "scanner.c"

#define INITIAL 0
#define LINECOMMENT 1
#define FULLCOMMENT 2
#define CLAY 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 90 "source/scanner.l"

#line 1001 "scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 372 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 580 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 91 "source/scanner.l"
{
                              scanner_column += 2;
                              scanner_comment--;
                              if (scanner_comment == 0)
                                BEGIN INITIAL;      /* Quit any mode */
                            }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 97 "source/scanner.l"
{
                              scanner_column += 2;
                              scanner_comment++;
                            }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 101 "source/scanner.l"
{
                              scanner_line++;
                              scanner_column = 1;
                              if (scanner_parsing) {
			        CLAN_realloc(scanner_clay, char *,
                                    (strlen(scanner_clay) + 2) * sizeof(char));
                                strcat(scanner_clay, yytext);
			      }
                            }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 110 "source/scanner.l"
{
                              scanner_column++;
                              if (scanner_parsing) {
                                CLAN_realloc(scanner_clay, char *,
                                    (strlen(scanner_clay) + 2) * sizeof(char));
                                strcat(scanner_clay, yytext);
			      }
                            }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 118 "source/scanner.l"
{
                              scanner_column += 2;
                              scanner_comment--;
                              if (scanner_comment == 0)
                                BEGIN INITIAL;      /* Quit any mode */
                            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 124 "source/scanner.l"
{ 
                              scanner_column += 2;
                              scanner_comment++;
                            }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 128 "source/scanner.l"
{
                              scanner_line++;       /* Do nothing */
                              scanner_column = 1;
                            }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 132 "source/scanner.l"
{ scanner_column++;     /* Do nothing */ }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 133 "source/scanner.l"
{ 
                              scanner_line++;
                              scanner_column = 1;
                              BEGIN INITIAL;        /* Quit any mode */
                            }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "source/scanner.l"
{ scanner_column++;     /* Do nothing */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 139 "source/scanner.l"
{ 
                              scanner_column += 2;
                              BEGIN LINECOMMENT;    /* Enter LINECOMMENT mode*/
                            }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 143 "source/scanner.l"
{
                              scanner_column = 1;
                              scanner_line++;
			      if (scanner_comment == 0)
				BEGIN CLAY;         /* Enter CLAY mode*/
			      else
                                BEGIN FULLCOMMENT;  /* Enter FULLCOMMENT mode*/
                              scanner_comment++;
                            }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 152 "source/scanner.l"
{
                              scanner_column += 2;
                              BEGIN FULLCOMMENT;    /* Enter FULLCOMMENT mode*/
                              scanner_comment++;
                            }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 158 "source/scanner.l"
{ return clan_scanner(AUTO, "auto"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 159 "source/scanner.l"
{ return clan_scanner(BOOL, "_Bool"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 160 "source/scanner.l"
{ return clan_scanner(BREAK, "break"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 161 "source/scanner.l"
{ return clan_scanner(CASE, "case"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 162 "source/scanner.l"
{ return clan_scanner(CHAR, "char"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 163 "source/scanner.l"
{ return clan_scanner(COMPLEX, "_Complex"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 164 "source/scanner.l"
{ return clan_scanner(CONST, "const"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 165 "source/scanner.l"
{ return clan_scanner(CONTINUE, "continue"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 166 "source/scanner.l"
{ return clan_scanner(DEFAULT, "default"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 167 "source/scanner.l"
{ return clan_scanner(DO, "do"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 168 "source/scanner.l"
{ return clan_scanner(DOUBLE, "double"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 169 "source/scanner.l"
{ return clan_scanner(ELSE, "else"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 170 "source/scanner.l"
{ return clan_scanner(ENUM, "enum"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 171 "source/scanner.l"
{ return clan_scanner(EXTERN, "extern"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 172 "source/scanner.l"
{ return clan_scanner(FLOAT, "float"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 173 "source/scanner.l"
{ return clan_scanner(FOR, "for"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 174 "source/scanner.l"
{ return clan_scanner(GOTO, "goto"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 175 "source/scanner.l"
{ return clan_scanner(IF, "if"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 176 "source/scanner.l"
{ return clan_scanner(IMAGINARY, "_Imaginary"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 177 "source/scanner.l"
{ return clan_scanner(INLINE, "inline"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 178 "source/scanner.l"
{ return clan_scanner(INT, "int"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 179 "source/scanner.l"
{ return clan_scanner(LONG, "long"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 180 "source/scanner.l"
{ return clan_scanner(REGISTER, "register"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 181 "source/scanner.l"
{ return clan_scanner(RESTRICT, "restrict"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 182 "source/scanner.l"
{ return clan_scanner(RETURN, "return"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 183 "source/scanner.l"
{ return clan_scanner(SHORT, "short"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 184 "source/scanner.l"
{ return clan_scanner(SIGNED, "signed"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 185 "source/scanner.l"
{ return clan_scanner(SIZEOF, "sizeof"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 186 "source/scanner.l"
{ return clan_scanner(STATIC, "static"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 187 "source/scanner.l"
{ return clan_scanner(STRUCT, "struct"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 188 "source/scanner.l"
{ return clan_scanner(SWITCH, "switch"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 189 "source/scanner.l"
{ return clan_scanner(TYPEDEF, "typedef"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 190 "source/scanner.l"
{ return clan_scanner(UNION, "union"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 191 "source/scanner.l"
{ return clan_scanner(UNSIGNED, "unsigned"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 192 "source/scanner.l"
{ return clan_scanner(VOID, "void"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 193 "source/scanner.l"
{ return clan_scanner(VOLATILE, "volatile"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 194 "source/scanner.l"
{ return clan_scanner(WHILE, "while"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 195 "source/scanner.l"
{ return clan_scanner(MIN, "min"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 196 "source/scanner.l"
{ return clan_scanner(MAX, "max"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 197 "source/scanner.l"
{ return clan_scanner(CEILD, "ceild"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 198 "source/scanner.l"
{ return clan_scanner(FLOORD, "floord"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 200 "source/scanner.l"
{ 
                              clan_scanner_count();
                              scanner_scop_start = scanner_line;
                              if (parser_options->autoscop) {
                                scanner_pragma = CLAN_TRUE;
                                scanner_parsing = CLAN_FALSE;
                                CLAN_debug("pragma scop: stop parsing");
                                return PRAGMA; // Force a parse error.
                              } else {
                                scanner_parsing = CLAN_TRUE;
                                CLAN_debug("pragma scop: start parsing");
                              }
                            }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 213 "source/scanner.l"
{
                              clan_scanner_count();
                              scanner_scop_end = scanner_line;
                              if (parser_options->autoscop) {
                                scanner_pragma = CLAN_FALSE;
                                scanner_parsing = CLAN_TRUE;
                                CLAN_debug("pragma endscop: start parsing");
                                return PRAGMA; // Force a parse error.
                              } else {
                                scanner_parsing = CLAN_FALSE;
                                CLAN_debug("pragma endscop: stop parsing");
                                return IGNORE;
                              }
                            }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 228 "source/scanner.l"
{
                              if (scanner_parsing == CLAN_TRUE) { 
                                CLAN_strdup(yylval.symbol, yytext);
                              }
                              return clan_scanner(ID, "ID");
                            }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 234 "source/scanner.l"
{
                              yylval.value = atoi(yytext) ;
                              return clan_scanner(INTEGER, "INTEGER");
                            }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 238 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_0"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 239 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_1"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 240 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_2"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 241 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_3"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 242 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_4"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 243 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_5"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 244 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_6"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 245 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_7"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 246 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_8"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 247 "source/scanner.l"
{ return clan_scanner(CONSTANT, "CONSTANT_9"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 248 "source/scanner.l"
{ return clan_scanner(STRING_LITERAL, "STRING"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 250 "source/scanner.l"
{ return clan_scanner(ELLIPSIS, "..."); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 251 "source/scanner.l"
{ return clan_scanner(RIGHT_ASSIGN, ">>="); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 252 "source/scanner.l"
{ return clan_scanner(LEFT_ASSIGN, "<<="); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 253 "source/scanner.l"
{ return clan_scanner(ADD_ASSIGN, "+="); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 254 "source/scanner.l"
{ return clan_scanner(SUB_ASSIGN, "-="); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 255 "source/scanner.l"
{ return clan_scanner(MUL_ASSIGN, "*="); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 256 "source/scanner.l"
{ return clan_scanner(DIV_ASSIGN, "/="); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 257 "source/scanner.l"
{ return clan_scanner(MOD_ASSIGN, "%="); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 258 "source/scanner.l"
{ return clan_scanner(AND_ASSIGN, "&="); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 259 "source/scanner.l"
{ return clan_scanner(XOR_ASSIGN, "^="); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 260 "source/scanner.l"
{ return clan_scanner(OR_ASSIGN, "|="); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 261 "source/scanner.l"
{ return clan_scanner(RIGHT_OP, ">>"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 262 "source/scanner.l"
{ return clan_scanner(LEFT_OP, "<<"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 263 "source/scanner.l"
{ return clan_scanner(INC_OP, "++"); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 264 "source/scanner.l"
{ return clan_scanner(DEC_OP, "--"); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 265 "source/scanner.l"
{ return clan_scanner(PTR_OP, "->"); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 266 "source/scanner.l"
{ return clan_scanner(AND_OP, "&&"); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 267 "source/scanner.l"
{ return clan_scanner(OR_OP, "||"); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 268 "source/scanner.l"
{ return clan_scanner(LE_OP, "<="); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 269 "source/scanner.l"
{ return clan_scanner(GE_OP, ">="); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 270 "source/scanner.l"
{ return clan_scanner(EQ_OP, "=="); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 271 "source/scanner.l"
{ return clan_scanner(NE_OP, "!="); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 272 "source/scanner.l"
{ return clan_scanner(';', ";"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 273 "source/scanner.l"
{ return clan_scanner('{', "{"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 274 "source/scanner.l"
{ return clan_scanner('}', "}"); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 275 "source/scanner.l"
{ return clan_scanner(',', ","); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 276 "source/scanner.l"
{ return clan_scanner(':', ":"); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 277 "source/scanner.l"
{ return clan_scanner('=', "="); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 278 "source/scanner.l"
{ return clan_scanner('(', "("); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 279 "source/scanner.l"
{ return clan_scanner(')', ")"); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 280 "source/scanner.l"
{ return clan_scanner('[', "["); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 281 "source/scanner.l"
{ return clan_scanner(']', "]"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 282 "source/scanner.l"
{ return clan_scanner('.', "."); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 283 "source/scanner.l"
{ return clan_scanner('&', "&"); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 284 "source/scanner.l"
{ return clan_scanner('!', "!"); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 285 "source/scanner.l"
{ return clan_scanner('~', "~"); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 286 "source/scanner.l"
{ return clan_scanner('-', "-"); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 287 "source/scanner.l"
{ return clan_scanner('+', "+"); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 288 "source/scanner.l"
{ return clan_scanner('*', "*"); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 289 "source/scanner.l"
{ return clan_scanner('/', "/"); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 290 "source/scanner.l"
{ return clan_scanner('%', "%"); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 291 "source/scanner.l"
{ return clan_scanner('<', "<"); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 292 "source/scanner.l"
{ return clan_scanner('>', ">"); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 293 "source/scanner.l"
{ return clan_scanner('^', "^"); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 294 "source/scanner.l"
{ return clan_scanner('|', "|"); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 295 "source/scanner.l"
{ return clan_scanner('?', "?"); }
	YY_BREAK
case 116:
/* rule 116 can match eol */
YY_RULE_SETUP
#line 296 "source/scanner.l"
{ clan_scanner_count();
                              // A list of separators is translated to a
                              // single space. We proceed one by one to
                              // compute precise coordinates.
                              if (parser_record &&
                                  parser_recording &&
                                  !scanner_space) {
                                char* space;
                                CLAN_malloc(space, char*, 2);
                                CLAN_realloc(parser_record, char*,
                                             (strlen(parser_record) + 2) *
                                             sizeof(char));
                                space[0] = ' ';
                                space[1] = '\0';
                                // FIXME: just to please valgrind, I'm not
                                // using strcat(parser_record, " "). Strange.
                                strcat(parser_record, space);
                                free(space);
                                scanner_space = CLAN_TRUE;
                              }
                            }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 317 "source/scanner.l"
{ 
                              scanner_column++;
                              CLAN_debug("unmatched characters by Lex");
                            }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 321 "source/scanner.l"
ECHO;
	YY_BREAK
#line 1762 "scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINECOMMENT):
case YY_STATE_EOF(FULLCOMMENT):
case YY_STATE_EOF(CLAY):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 372 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 372 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 371);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 321 "source/scanner.l"



/**
 * clan_scanner_initialize function:
 * this function initialises the scanner global variables with default values.
 */
void clan_scanner_initialize() {
  yy_buffer_stack_top = 0;
  yy_buffer_stack = 0;
  yy_flush_buffer(YY_CURRENT_BUFFER);
  scanner_parsing = CLAN_FALSE;
  scanner_comment = 0;
  scanner_latest_text = NULL;
  CLAN_malloc(scanner_clay, char *, sizeof(char));
  scanner_clay[0] = '\0';
  scanner_line = 1;
  scanner_column = 1;
  scanner_column_LALR = 1;
  scanner_pragma = CLAN_FALSE;
  scanner_space = CLAN_FALSE;
  scanner_scop_start = CLAN_UNDEFINED;
  scanner_scop_end = CLAN_UNDEFINED;
}


/**
 * clan_scanner_reinitialize function:
 * this function frees the temporary dynamic variables of the scanner and
 * and reset the variables to default or input values. It is meant to
 * be used for a clean restart after a parse error.
 * \param[in] pragma The initialization value of scanner_pragma.
 * \param[in] line   The initialization value of scanner_line.
 * \param[in] column The initialization value of scanner_column.
 */
void clan_scanner_reinitialize(int pragma, int line, int column) {
  free(scanner_latest_text);
  free(scanner_clay);
  clan_scanner_initialize();
  scanner_pragma = pragma;
  scanner_line = line;
  scanner_column = column;
}


/**
 * clan_scanner_count function:
 * this function updates the current line and column the scanner is reading.
 */
void clan_scanner_count() {
  int i;

  scanner_column_LALR = scanner_column;
  for (i = 0; yytext[i] != '\0'; i++) {
    if (yytext[i] == '\n') {
      scanner_line++;
      scanner_column = 1;
    } else {
      scanner_column++;
    }
  }
}


/**
 * clan_scanner_free function:
 * this function frees the memory allocated for the scanner. It frees
 * flex's buffer (it supposes there is only one buffer) since flex does
 * never free it itself.
 * WARNING: this is probably *not* portable...
 */
void clan_scanner_free() {
  yy_delete_buffer(YY_CURRENT_BUFFER);
  free(yy_buffer_stack);
  free(scanner_latest_text);
  scanner_latest_text = NULL;
  free(scanner_clay);
  scanner_clay = NULL;
}


/**
 * clan_scanner function:
 * This function achieves some basic work when Lex recognize something: it
 * prints a log information if necessary for debugging, it updates the string
 * scanner_latest_text with the string that have been read and returns the
 * token if we are scanning a SCoP or the special token IGNORE otherwise.
 * \param token   The token code to send to Yacc for the Lex item.
 * \param message A string to be printed for debugging.
 */
int clan_scanner(int token, char* message) {
  if (CLAN_DEBUG)
    fprintf(stderr, "[Clan] Debug: Lex yytext = %s "
                    "(%s at line %d, column %d)\n",
                    message, yytext, scanner_line, scanner_column);
  clan_scanner_count();
  
  free(scanner_latest_text);
  scanner_latest_text = strdup(yytext);
  if (parser_recording) {
    CLAN_realloc(parser_record, char*,
                 (strlen(parser_record) + strlen(yytext) + 1) * sizeof(char));
    strcat(parser_record, yytext);
    scanner_space = CLAN_FALSE;
  }
  
  if (scanner_parsing == CLAN_TRUE)
    return token;
  else
    return IGNORE;
}

